Add dapp list and banner list for dapp browser
DcentWallet/info pull request #2
Opened 2020-09-09 08:07 UTC by KyungeunKim

DApp browser 에서 표시하는 배너와 DApp List 를 추가

2020-09-09 11:00 UTC, paromix requested changes

2020-09-09 11:00 UTC, paromix commented on dapp/dapplist.json
> +                "ko": "1inch Exchange는 모든 주요 DEX 거래소의 유동성과 가격 정보를 하나의 플랫폼에서 제공합니다. 원하는 거래의 가격을 쉽게 조회하여 토큰을 교환할 수 있습니다.",
유니스왑인데 설명이 1inch로..^^
그리고 유니스왑이랑 1inch랑 순서바꾸는게 좋을 것 같아요~ 유니스왑 먼저

2020-09-09 23:49 UTC, KyungeunKim commented on dapp/dapplist.json
> +                "ko": "1inch Exchange는 모든 주요 DEX 거래소의 유동성과 가격 정보를 하나의 플랫폼에서 제공합니다. 원하는 거래의 가격을 쉽게 조회하여 토큰을 교환할 수 있습니다.",
앗! 김차장님한테 설명 문구 받은 후에 적용하려고 했는데..  성급하게 해버렸네요..;;  
반영되면 다시 리뷰 신청할게요..^^

2020-09-10 00:20 UTC, paromix commented on dapp/dapplist.json
> +                "ko": "1inch Exchange는 모든 주요 DEX 거래소의 유동성과 가격 정보를 하나의 플랫폼에서 제공합니다. 원하는 거래의 가격을 쉽게 조회하여 토큰을 교환할 수 있습니다.",
설명 문구는 일단 제가 어제 써드린 걸로 쓰시지요~

영문 : Uniswap is a fully decentralized protocol for automated liquidity provision on Ethereum.
한글 : 유니스왑은 유동성을 공급하고 토큰을 교환할 수 있는 이더리움 기반의 자동화된 탈중앙 프로토콜입니다.

2020-09-10 00:22 UTC, paromix approved these changes

2020-09-10 01:22 UTC, SeungjunWe approved these changes

2020-09-10 03:29 UTC, merged