#311 리셀러 목록 수정 및 링크 변경
DcentWallet/info pull request #312
Opened 2024-08-30 06:55 UTC by YonghunKim123

일부 리셀러 제거 및 링크 수정하였습니다.

2024-08-30 07:02 UTC, SeungjunWe requested changes

2024-08-30 07:02 UTC, SeungjunWe commented on reseller/reseller-list-en.json
> +    "gotoLink": "https://siambc.com/shop/all-products/dcent-hw-wallet-authorised-reseller-%e0%b8%95[…]e0%b9%88%e0%b8%b2%e0%b8%a2%e0%b8%ad%e0%b8%a2%e0%b9%88%e0%b8%b2/"
링크가 이상해요

2024-08-30 08:37 UTC, SeungjunWe approved these changes

2024-09-02 00:35 UTC, KyungeunKim approved these changes

2024-09-02 00:35 UTC, merged