Feature/spark airdrop
DcentWallet/info pull request #4
Opened 2020-10-05 07:45 UTC by lix82

Spark Airdrop 서비스 추가

2020-10-05 08:01 UTC, paromix commented
@KyungeunKim 
이거 마스터로 머지되면 사용자들에게 보이는 것 아닌가요? 이 리스트는 별도의 프리가 없었던 것 같은데요.

2020-10-05 08:02 UTC, KyungeunKim commented
> @KyungeunKim
> 이거 마스터로 머지되면 사용자들에게 보이는 것 아닌가요? 이 리스트는 별도의 프리가 없었던 것 같은데요.

넵! 바로 merge하면 보입니다. 실제 릴리즈시에 merge 해야 합니다.

2020-10-05 08:03 UTC, paromix reviewed
dapp/dapplist.json 요것과
dapp/en/dapplist.json , dapp/ko/dapplist.json 
요 리스트의 차이는 무엇인가요?

2020-10-05 08:04 UTC, KyungeunKim commented
> dapp/dapplist.json 요것과
> dapp/en/dapplist.json , dapp/ko/dapplist.json
> 요 리스트의 차이는 무엇인가요?

dapp/dapplist.json 이건 예전에 사용하던 dapp list 로.. 이제 더이상 사용하지 않습니다.
삭제해도 됩니다.

2020-10-05 09:45 UTC, paromix requested changes

2020-10-06 04:51 UTC, paromix approved these changes
머지는 최종 릴리즈때 되는거죠?^^

2020-10-06 04:57 UTC, KyungeunKim approved these changes
Merge는 최종 릴리즈시 해주세요.

2020-10-06 05:01 UTC, paromix commented
프리때 테스트할 수 있는 방법이 있으면 좋을 것 같기는 하네요.^^
나중에 댑 리스트를 대폭 확대할 때에는 필요할 것 같아요. @KyungeunKim

2020-10-06 09:15 UTC, merged